### Create long running testjob
// @no-log
POST http://{{server}}:8000/jobs/?seconds=5
Content-Type: application/json
Accept: application/json

> {%
    client.global.set("href_ws", response.body.href_ws);
%}

### Connect to websocket of created job

WEBSOCKET ws://{{server}}:8000{{href_ws}}/

> {%
    var i = 0
    response.body.onEachMessage((message, unsubscribe, output) => {
        client.log(message);
    }, () => {
        client.log("We stopped listening for WebSocket from the current 'onEachMessage' call!")
    });
%}
